import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient('https://uqmnpeovwfzizajheuig.supabase.co','sb_publishable_W6N3YZeKf9iMSpQMt4Oukw_rmLfRTap');
const trigger=document.getElementById('batchVideoBtn');
const msg=document.getElementById('quickGenerateMessage');
let overlay=null;
const clean=v=>String(v||'').replace(/[\r\n]+/g,' ').trim().slice(0,180);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function shortCopy(topic,index){const hook=`${topic} has one detail that changes how the whole subject makes sense.`;const beats=[hook,`Start with the obvious version of ${topic}, then look one layer deeper.`,`The important part is the connection between what people notice first and the mechanism underneath it.`,`That connection creates a consequence, and the consequence is more useful than a list of disconnected facts.`,`Now flip the perspective: instead of asking what ${topic} is, ask what changes because of it.`,`That question reveals the part worth remembering, because it turns a passing subject into a pattern you can recognize again.`,`The takeaway is simple: ${topic} matters most when you understand the chain behind the visible result.`];return {hook,script:beats.join(' '),title:`${topic}: The Detail That Changes the Story`.slice(0,100),style:index%3===0?'Documentary':index%3===1?'Mystery':'Educational'};}
async function addPipeline(userId,projectId,longform){const rows=['research','script_writer','script','creative_preflight','voice','visuals','edit','sound_design','final_video_qc','quality_check','ready'].map(step=>({user_id:userId,project_id:projectId,step,status:step==='research'?'passed':'pending',detail:step==='research'?'Batch project created without unsupported factual claims; verified research is still required when factual claims are added.':null}));if(!longform)rows.find(x=>x.step==='script').status='passed';await supabase.from('project_pipeline_steps').insert(rows);}
async function createOne(user,topic,longform,index){const base=shortCopy(topic,index);const payload={user_id:user.id,title:longform?`${topic}: Full Story`.slice(0,100):base.title,topic,format:longform?'Long-form':'Short',style:base.style,target_duration_seconds:longform?600:50,status:'generating',hook:longform?'':base.hook,script:longform?'':base.script};const {data:project,error}=await supabase.from('video_projects').insert(payload).select().single();if(error)throw error;await addPipeline(user.id,project.id,longform);if(!longform)await supabase.from('hook_variants').insert({user_id:user.id,project_id:project.id,hook:base.hook,selected:true});const {error:re}=await supabase.from('render_jobs').insert({user_id:user.id,project_id:project.id,engine:'motion-first-renderer-v10-retention',status:'queued'});if(re)throw re;return project;}
async function dispatch(token){try{await fetch('/api/render-now',{method:'POST',headers:{Authorization:`Bearer ${token}`}});}catch{}}
function close(){overlay?.remove();overlay=null;}
function open(){close();overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;z-index:10000;background:rgba(0,0,0,.74);display:flex;align-items:center;justify-content:center;padding:16px';overlay.innerHTML=`<section style="width:min(720px,100%);max-height:90vh;overflow:auto;background:#11141d;border:1px solid rgba(255,255,255,.14);border-radius:22px;padding:20px"><div class="section-head"><div><div class="eyebrow">BATCH VIDEO</div><h2 style="margin:5px 0">Queue multiple videos</h2></div><button class="ghost compact" data-close>Close</button></div><p class="muted small">Enter one topic per line. Each video is created separately and must pass creative and finished-video QC before it can publish.</p><label class="field-label">Video type<select data-kind style="width:100%;margin-top:6px"><option value="short">Shorts — about 50 seconds each</option><option value="long">Full videos — about 10 minutes each</option></select></label><label class="field-label" style="display:block;margin-top:14px">Topics<textarea data-topics rows="12" maxlength="4000" placeholder="The ocean has waterfalls\nWhy the moon is moving away\nHow forests communicate underground" style="width:100%;margin-top:6px"></textarea></label><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:12px"><span class="muted small" data-count>0 / 25 topics</span><button class="primary" data-create>Queue batch</button></div><p class="status-line" data-status></p></section>`;document.body.appendChild(overlay);overlay.onclick=e=>{if(e.target===overlay)close();};overlay.querySelector('[data-close]').onclick=close;const ta=overlay.querySelector('[data-topics]'),count=overlay.querySelector('[data-count]'),status=overlay.querySelector('[data-status]'),create=overlay.querySelector('[data-create]');const parsed=()=>ta.value.split(/\n+/).map(clean).filter(Boolean).slice(0,25);ta.oninput=()=>count.textContent=`${parsed().length} / 25 topics`;create.onclick=async()=>{const topics=parsed();if(!topics.length){status.textContent='Add at least one topic.';return;}create.disabled=true;const longform=overlay.querySelector('[data-kind]').value==='long';try{const {data:{session}}=await supabase.auth.getSession();const {data:{user}}=await supabase.auth.getUser();if(!session?.access_token||!user)throw new Error('Sign in first.');let made=0;for(let i=0;i<topics.length;i++){status.textContent=`Creating ${i+1} of ${topics.length}: ${esc(topics[i])}`;await createOne(user,topics[i],longform,i);made++;}await dispatch(session.access_token);msg.textContent=`Batch queued: ${made} ${longform?'full-length videos':'Shorts'}. Every video must pass QC before publishing.`;close();setTimeout(()=>location.reload(),1200);}catch(e){status.textContent=e?.message||'Batch creation failed.';create.disabled=false;}};}
trigger?.addEventListener('click',open);
