const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function style(){
 if(document.getElementById('blackstarUiStyles'))return;
 const s=document.createElement('style');s.id='blackstarUiStyles';s.textContent=`
 #blackstar .bs-hero{display:grid;grid-template-columns:1.5fr 1fr;gap:24px;padding:28px;border:1px solid rgba(97,218,251,.22);background:linear-gradient(135deg,rgba(4,9,17,.98),rgba(8,20,30,.94));border-radius:22px;overflow:hidden;position:relative}#blackstar .bs-hero:after{content:'★';position:absolute;right:28px;top:4px;font-size:150px;color:rgba(90,220,255,.06)}#blackstar .bs-title{font-size:clamp(38px,6vw,72px);letter-spacing:.12em;margin:4px 0 8px}
 #blackstar .bs-head{display:flex;justify-content:space-between;align-items:end;gap:16px;margin:26px 0 12px}.bs-head h3{margin:3px 0 0}.bs-strip{display:grid;grid-template-columns:repeat(5,minmax(180px,1fr));gap:12px;overflow-x:auto;padding-bottom:6px}.bs-strip.rival{grid-template-columns:repeat(4,minmax(190px,1fr))}
 #blackstar .bs-card{background:rgba(10,16,26,.92);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:18px}.bs-op{padding:0!important;overflow:hidden;cursor:pointer;transition:.18s}.bs-op:hover{transform:translateY(-3px);border-color:rgba(90,223,255,.35)}.bs-op.rival:hover{border-color:rgba(211,83,72,.5)}
 #blackstar .bs-art{height:245px;background:#060a11;border-bottom:1px solid rgba(255,255,255,.08)}.bs-art svg{width:100%;height:100%;display:block}.bs-cap{padding:12px 13px 15px}.bs-cap strong{display:block;color:#f4f9ff}.bs-cap .role{display:block;color:#7dd3fc;font-size:11px;text-transform:uppercase;letter-spacing:.07em;margin-top:4px}.bs-op.rival .role{color:#f18a80}.bs-cap small{display:block;margin-top:7px;line-height:1.35;color:#9aa8b8}
 #blackstar .bs-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.bs-subtab{border:1px solid rgba(255,255,255,.12);background:#0b111b;color:#cbd5e1;border-radius:999px;padding:9px 14px;cursor:pointer}.bs-subtab.active{border-color:#5adfff;color:white;background:#112838}.bs-panel{display:none}.bs-panel.active{display:block}.bs-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px}.bs-meta{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#7dd3fc}.bs-chip{display:inline-block;padding:4px 8px;border-radius:999px;background:rgba(90,223,255,.12);color:#8fe8ff;font-size:12px;margin:2px}.bs-story{white-space:pre-wrap;line-height:1.7}.bs-warning{border-left:3px solid #f59e0b;padding-left:12px}.bs-rival{border-left:3px solid #cc5149;background:linear-gradient(90deg,rgba(204,81,73,.12),transparent);padding:14px 16px;margin:10px 0 18px}
 #blackstar .bs-dossier{padding:0!important;overflow:hidden}.bs-dossier .bs-art{height:300px}.bs-copy{padding:18px}.bs-copy p{line-height:1.55}.bs-ability{border:1px solid rgba(90,223,255,.2);background:rgba(90,223,255,.05);border-radius:12px;padding:12px;margin:12px 0}.bs-rival-dossier .bs-ability{border-color:rgba(204,81,73,.3);background:rgba(204,81,73,.06)}
 #blackstar .bs-armory{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.bs-weapon{padding:0!important;overflow:hidden}.bs-weapon-art{height:120px;background:linear-gradient(135deg,#080d15,#121b27);display:grid;place-items:center;border-bottom:1px solid rgba(255,255,255,.08)}.bs-weapon-art svg{width:100%;height:100%}.bs-weapon-copy{padding:15px}.bs-weapon-copy h3{margin:4px 0 7px}.bs-weapon-copy p{line-height:1.45}.bs-merch{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.bs-merch-art{aspect-ratio:16/10;border-radius:14px;background:radial-gradient(circle at 50% 35%,rgba(90,223,255,.22),rgba(4,9,17,.96) 58%);display:grid;place-items:center;font-weight:800;letter-spacing:.12em;color:#dff8ff;border:1px dashed rgba(90,223,255,.35);text-align:center;padding:18px}.bs-status{display:flex;gap:10px;align-items:center}.bs-dot{width:9px;height:9px;border-radius:50%;background:#f59e0b}.bs-dot.ok{background:#22c55e}
 @media(max-width:900px){#blackstar .bs-hero{grid-template-columns:1fr}.bs-strip{grid-template-columns:repeat(5,185px)}.bs-strip.rival{grid-template-columns:repeat(4,195px)}#blackstar .bs-head{align-items:flex-start;flex-direction:column}}
 `;document.head.appendChild(s);
}
async function loadBible(){const r=await fetch('./episodes/blackstar-s01e01/show-bible.json',{cache:'no-store'});if(!r.ok)throw new Error('Could not load BLACKSTAR show bible.');return r.json();}

const looks={
 MARA_VOSS:{skin:'#8b5f46',hair:'#17191d',accent:'#46d7ff',gear:'#263746',eye:'#3b241b',mark:'01',hairStyle:'crop'},
 JAX_MERCER:{skin:'#5f3a2b',hair:'#111318',accent:'#f2a13b',gear:'#34383d',eye:'#5c4c2d',mark:'HX',hairStyle:'shaved'},
 IMANI_VALE:{skin:'#8a5a40',hair:'#181317',accent:'#d9f3ff',gear:'#313b45',eye:'#5d6b58',mark:'VX',hairStyle:'curl'},
 ROOK:{skin:'#a06c4c',hair:'#111319',accent:'#77e2ff',gear:'#283642',eye:'#231d18',mark:'♜',hairStyle:'undercut'},
 KESTREL:{skin:'#72e5ff',hair:'#0b202b',accent:'#48dcff',gear:'#12303e',eye:'#e5ffff',mark:'K',hairStyle:'ai'},
 VEYR_COMMANDER:{skin:'#c9d1cf',hair:'#0c0f12',accent:'#9ff6e7',gear:'#394246',eye:'#050607',mark:'III',hairStyle:'alien'},
 RV_KADE:{skin:'#c29373',hair:'#6b563c',accent:'#c9524a',gear:'#24262c',eye:'#49505a',mark:'RV',hairStyle:'crop'},
 RV_NYX:{skin:'#d4a584',hair:'#111216',accent:'#c9524a',gear:'#1d2128',eye:'#161514',mark:'NX',hairStyle:'bob'},
 RV_BRIGGS:{skin:'#9d6346',hair:'#1d1a19',accent:'#c9524a',gear:'#2b2d31',eye:'#3d2d24',mark:'BR',hairStyle:'short'},
 RV_SABLE:{skin:'#5f3a2d',hair:'#171419',accent:'#c9524a',gear:'#26272d',eye:'#704c2a',mark:'SB',hairStyle:'braids'}
};
function operatorVisual(c){
 const v=looks[c.id]||looks.MARA_VOSS;
 if(c.id==='KESTREL')return `<div class="bs-art"><svg viewBox="0 0 260 320"><rect width="260" height="320" fill="#050912"/><circle cx="130" cy="112" r="95" fill="#123642" opacity=".85"/><ellipse cx="130" cy="112" rx="48" ry="59" fill="#7feaff" opacity=".18" stroke="#7feaff" stroke-width="2"/><path d="M99 91 Q130 70 161 91" fill="none" stroke="#aef6ff" stroke-width="4"/><circle cx="113" cy="110" r="4" fill="#e5ffff"/><circle cx="147" cy="110" r="4" fill="#e5ffff"/><path d="M108 137 Q130 151 152 137" fill="none" stroke="#baf7ff" stroke-width="3"/><path d="M35 205 L96 164 L130 184 L164 164 L225 205 L188 230 L130 207 L72 230 Z" fill="#10303d" stroke="#49dcff" stroke-width="3"/><text x="130" y="286" text-anchor="middle" fill="#75e8ff" font-size="18" letter-spacing="5">KESTREL</text></svg></div>`;
 const alien=c.id==='VEYR_COMMANDER';const rival=c.team==='RED VECTOR';
 const hair=v.hairStyle==='shaved'?`<path d="M92 80 Q130 54 168 80 L163 91 Q130 72 97 91Z" fill="#151515"/>`:v.hairStyle==='bob'?`<path d="M80 74 Q130 36 180 74 L174 144 L156 110 Q130 82 104 110 L86 145Z" fill="${v.hair}"/>`:v.hairStyle==='curl'?`<path d="M86 78 Q87 48 108 54 Q123 38 137 54 Q158 42 173 70 Q185 88 169 106 L91 105 Q75 95 86 78Z" fill="${v.hair}"/>`:v.hairStyle==='braids'?`<path d="M84 77 Q130 43 176 77 L167 101 Q130 73 93 101Z" fill="${v.hair}"/><path d="M89 93 L77 165 M102 86 L91 165 M158 86 L169 165 M171 93 L182 165" stroke="${v.hair}" stroke-width="7"/>`:v.hairStyle==='undercut'?`<path d="M91 75 Q134 46 170 78 L156 91 Q126 70 98 96Z" fill="${v.hair}"/>`:`<path d="M91 78 Q130 50 169 78 L161 92 Q130 75 99 92Z" fill="${v.hair}"/>`;
 return `<div class="bs-art"><svg viewBox="0 0 260 320"><rect width="260" height="320" fill="#060a11"/><circle cx="130" cy="104" r="102" fill="${v.accent}" opacity=".08"/><path d="M57 320 L68 214 Q79 181 104 171 L156 171 Q181 181 192 214 L203 320Z" fill="${v.gear}" stroke="${v.accent}" stroke-width="2"/><path d="M79 224 L52 210 L42 275 L78 279Z M181 224 L208 210 L218 275 L182 279Z" fill="${rival?'#2a2528':'#293845'}" stroke="${v.accent}" stroke-width="2"/><path d="M100 154 L110 185 L150 185 L160 154Z" fill="${v.skin}"/><ellipse cx="130" cy="112" rx="49" ry="61" fill="${v.skin}" stroke="${alien?v.accent:'#17191d'}" stroke-width="2"/>${alien?`<path d="M89 83 L105 63 L130 55 L155 63 L171 83 L160 145 L130 165 L100 145Z" fill="#bfc9c7" opacity=".55" stroke="${v.accent}" stroke-width="3"/><ellipse cx="112" cy="110" rx="7" ry="10" fill="#050607"/><ellipse cx="148" cy="110" rx="7" ry="10" fill="#050607"/><path d="M108 139 Q130 146 152 139" stroke="${v.accent}" stroke-width="2" fill="none"/>`:`${hair}<ellipse cx="113" cy="112" rx="5" ry="4" fill="${v.eye}"/><ellipse cx="147" cy="112" rx="5" ry="4" fill="${v.eye}"/><path d="M109 139 Q130 147 151 139" fill="none" stroke="#4b2c27" stroke-width="2"/>${c.id==='MARA_VOSS'?`<path d="M148 83 L158 113" stroke="#6b3a35" stroke-width="2"/>`:''}${c.id==='JAX_MERCER'||c.id==='RV_BRIGGS'?`<path d="M103 139 Q130 160 157 139 L151 158 Q130 170 109 158Z" fill="#251c1a" opacity=".8"/>`:''}`}
 <path d="M93 187 L130 208 L167 187" fill="none" stroke="${v.accent}" stroke-width="4"/><rect x="104" y="224" width="52" height="31" rx="5" fill="#0b1117" stroke="${v.accent}"/><text x="130" y="246" text-anchor="middle" fill="${v.accent}" font-size="18" font-weight="800">${esc(v.mark)}</text><path d="M84 269 H176" stroke="${v.accent}" stroke-width="3" opacity=".7"/></svg></div>`;
}
function opCard(c,rival=false){return `<article class="bs-card bs-op ${rival?'rival':''}" data-cast-id="${esc(c.id)}">${operatorVisual(c)}<div class="bs-cap"><strong>${esc(c.name)}</strong><span class="role">${esc(c.role_callout||c.role)}</span><small>${esc(c.ability?.name||'')} · ${esc(c.weapon_id||'')}</small></div></article>`}
function dossier(c,rival=false){return `<article class="bs-card bs-dossier ${rival?'bs-rival-dossier':''}" id="character-${esc(c.id)}">${operatorVisual(c)}<div class="bs-copy"><div class="bs-meta">${esc(c.team||'BLACKSTAR')} · ${esc(c.role_callout||c.role)}</div><h3>${esc(c.name)}</h3><div class="bs-ability"><strong>${esc(c.ability?.name||'Ability')}</strong><p>${esc(c.ability?.description||'')}</p></div><p><strong>Audience reads the role:</strong> ${esc(c.audience_read||'')}</p><p><strong>Weapon:</strong> ${esc(c.weapon_id||'')}</p><p><strong>Speech:</strong> ${esc(c.speech||'')}</p><p><strong>Personality:</strong> ${esc(c.personality||'')}</p><p><strong>Look:</strong> ${esc(c.face||'')} ${esc(c.uniform||'')}</p><p><strong>Backstory:</strong> ${esc(c.backstory||'')}</p>${c.secret?`<p><strong>Secret:</strong> ${esc(c.secret)}</p>`:''}${c.season_arc?`<p><strong>Season arc:</strong> ${esc(c.season_arc)}</p>`:''}</div></article>`}
function weaponGraphic(w){const rival=(w.owner||'').match(/Kade|Nyx|Briggs|Sable/);const a=rival?'#cf5c52':'#59ddff';return `<div class="bs-weapon-art"><svg viewBox="0 0 360 120"><rect width="360" height="120" fill="#09101a"/><path d="M43 63 L92 43 L235 43 L270 54 L319 54 L319 69 L269 69 L235 81 L91 81Z" fill="#273441" stroke="${a}" stroke-width="3"/><path d="M126 81 L146 81 L139 108 L119 108Z" fill="#1b242e" stroke="${a}"/><rect x="196" y="31" width="51" height="14" rx="3" fill="#0a1018" stroke="${a}"/><circle cx="95" cy="62" r="9" fill="${a}" opacity=".65"/></svg></div>`}
function weaponCard(w){return `<article class="bs-card bs-weapon">${weaponGraphic(w)}<div class="bs-weapon-copy"><div class="bs-meta">${esc(w.owner)}</div><h3>${esc(w.name)}</h3><p>${esc(w.look)}</p><p class="muted small">${esc(w.story_use)}</p></div></article>`}
function episodeCard(e){return `<article class="bs-card"><div class="bs-meta">Episode ${e.number}</div><h3>${esc(e.title)}</h3><p>${esc(e.purpose)}</p></article>`}
function merchCard(p){return `<article class="bs-card"><div class="bs-merch-art">${esc(p.name)}<br><small>${esc(p.sku)}</small></div><h3>${esc(p.name)}</h3><p>${esc(p.art)}</p><p class="muted small">Placement: ${esc(p.placement)}</p><button class="ghost compact" data-bs-merch="${esc(p.sku)}">Prepare product</button></article>`}

function render(root,b){const black=b.characters.filter(c=>c.team==='BLACKSTAR');const veyr=b.characters.filter(c=>c.team!=='BLACKSTAR');const red=b.opposing_team?.members||[];root.innerHTML=`
 <section class="bs-hero"><div><div class="eyebrow">ORIGINAL SERIES COMMAND</div><h2 class="bs-title">${esc(b.show.title)}</h2><p style="font-size:20px">${esc(b.show.tagline)}</p><p class="muted">${esc(b.show.premise)}</p><div>${b.show.themes.map(x=>`<span class="bs-chip">${esc(x)}</span>`).join('')}</div></div><div class="bs-card"><div class="bs-meta">Visual doctrine</div><h3>Readable tactical operators</h3><p>${esc(b.show.role_readability_rule)}</p><p class="muted small">${esc(b.show.visual_identity)}</p></div></section>
 <div class="bs-head"><div><div class="bs-meta">BLACKSTAR</div><h3>Primary operators</h3></div><span class="muted small">Faces, clothes, role, ability and weapon are persistent canon.</span></div><section class="bs-strip">${black.map(c=>opCard(c)).join('')}</section>
 <div class="bs-head"><div><div class="bs-meta">Opposing team</div><h3>${esc(b.opposing_team.name)}</h3></div><span class="muted small">Human rivals with different tactics—not simple villains.</span></div><div class="bs-rival"><strong>${esc(b.opposing_team.alignment)}</strong><p>${esc(b.opposing_team.purpose)}</p></div><section class="bs-strip rival">${red.map(c=>opCard(c,true)).join('')}</section>
 <div class="bs-tabs">${['overview','script','operators','armory','lore','production','audio','merch'].map((x,i)=>`<button class="bs-subtab ${i?'':'active'}" data-bs-tab="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div>
 <section class="bs-panel active" data-bs-panel="overview"><div class="bs-grid"><article class="bs-card"><div class="bs-meta">Season One</div><h3>Complete season arc</h3><p>${esc(b.season_one.arc)}</p></article><article class="bs-card"><div class="bs-meta">Episode One</div><h3>${esc(b.episode_one.title)}</h3><p>${esc(b.episode_one.full_story)}</p></article></div><h3>Season map</h3><div class="bs-grid">${b.season_one.episodes.map(episodeCard).join('')}</div></section>
 <section class="bs-panel" data-bs-panel="script"><article class="bs-card"><div class="bs-meta">Story treatment</div><h3>S1E1 — ${esc(b.episode_one.title)}</h3><p class="bs-story">${esc(b.episode_one.full_story)}</p><p class="bs-warning"><strong>Violence rule:</strong> ${esc(b.episode_one.death_and_danger_rule)}</p><a class="ghost compact" href="./episodes/blackstar-s01e01/episode.json" target="_blank" rel="noopener">Open 20-segment production script</a></article></section>
 <section class="bs-panel" data-bs-panel="operators"><h3>BLACKSTAR</h3><div class="bs-grid">${black.map(c=>dossier(c)).join('')}</div><h3 style="margin-top:28px">RED VECTOR</h3><div class="bs-grid">${red.map(c=>dossier(c,true)).join('')}</div><h3 style="margin-top:28px">Veyr</h3><div class="bs-grid">${veyr.map(c=>dossier(c,true)).join('')}</div></section>
 <section class="bs-panel" data-bs-panel="armory"><div class="bs-warning"><strong>Fictional armory:</strong> weapons are story props with no real-world construction instructions.</div><div class="bs-armory" style="margin-top:16px">${(b.weapons||[]).map(weaponCard).join('')}</div></section>
 <section class="bs-panel" data-bs-panel="lore"><div class="bs-grid">${b.easter_eggs.map(e=>`<article class="bs-card"><div class="bs-meta">${esc(e.id)}</div><h3>Seed</h3><p>${esc(e.seed)}</p><h4>Payoff</h4><p>${esc(e.payoff)}</p></article>`).join('')}</div></section>
 <section class="bs-panel" data-bs-panel="production"><div class="bs-grid"><article class="bs-card"><div class="bs-meta">Animation direction</div><h3>Animation targets</h3>${b.episode_one.animation_targets.map(x=>`<p>• ${esc(x)}</p>`).join('')}</article><article class="bs-card"><div class="bs-meta">Role language</div><h3>Show, don't lecture</h3><p>${esc(b.show.role_readability_rule)}</p><p>Breaches, frag pushes, denied lanes, disabled gadgets, recon tracks and support interventions should recur with the same visual grammar so viewers learn the team organically.</p></article></div></section>
 <section class="bs-panel" data-bs-panel="audio"><div class="bs-grid"><article class="bs-card"><div class="bs-meta">Original score</div><h3>Soundtrack language</h3><p>${esc(b.episode_one.soundtrack)}</p></article><article class="bs-card"><div class="bs-meta">Sound design</div><h3>SFX palette</h3><p>${esc(b.episode_one.sfx)}</p></article></div></section>
 <section class="bs-panel" data-bs-panel="merch"><div class="bs-card"><div class="section-head"><div><div class="bs-meta">Store connection</div><h3>BLACKSTAR merchandise</h3></div><div class="bs-status"><span class="bs-dot"></span><span>${esc(b.merch.store_connection.status)}</span></div></div><p>${esc(b.merch.store_connection.note)}</p></div><div class="bs-merch" style="margin-top:16px">${b.merch.products.map(merchCard).join('')}</div></section>`;
 root.addEventListener('click',e=>{const t=e.target.closest('[data-bs-tab]');if(t){root.querySelectorAll('.bs-subtab').forEach(x=>x.classList.toggle('active',x===t));root.querySelectorAll('.bs-panel').forEach(x=>x.classList.toggle('active',x.dataset.bsPanel===t.dataset.bsTab));}const c=e.target.closest('[data-cast-id]');if(c){const btn=[...root.querySelectorAll('[data-bs-tab]')].find(x=>x.dataset.bsTab==='operators');btn?.click();setTimeout(()=>document.getElementById(`character-${CSS.escape(c.dataset.castId)}`)?.scrollIntoView({behavior:'smooth',block:'start'}),30);}const m=e.target.closest('[data-bs-merch]');if(m)alert(`BLACKSTAR ${m.dataset.bsMerch} is canon-approved for artwork/store mapping.`);});
}
async function init(){style();const root=document.getElementById('blackstarRoot');if(!root)return;root.innerHTML='<div class="panel">Loading BLACKSTAR canon…</div>';try{render(root,await loadBible())}catch(e){root.innerHTML=`<div class="panel"><strong>BLACKSTAR UI error</strong><p>${esc(e.message)}</p></div>`}}
init();
