const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function style(){
  if(document.getElementById('blackstarUiStyles')) return;
  const s=document.createElement('style'); s.id='blackstarUiStyles'; s.textContent=`
  #blackstar .bs-hero{display:grid;grid-template-columns:1.5fr 1fr;gap:24px;padding:28px;border:1px solid rgba(97,218,251,.22);background:linear-gradient(135deg,rgba(4,9,17,.98),rgba(8,20,30,.94));border-radius:22px;overflow:hidden;position:relative}
  #blackstar .bs-hero:after{content:'★';position:absolute;right:28px;top:4px;font-size:150px;color:rgba(90,220,255,.06)}
  #blackstar .bs-title{font-size:clamp(38px,6vw,72px);letter-spacing:.12em;margin:4px 0 8px}
  #blackstar .bs-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}.bs-subtab{border:1px solid rgba(255,255,255,.12);background:#0b111b;color:#cbd5e1;border-radius:999px;padding:9px 14px;cursor:pointer}.bs-subtab.active{border-color:#5adfff;color:white;background:#112838}
  #blackstar .bs-panel{display:none}#blackstar .bs-panel.active{display:block}
  #blackstar .bs-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.bs-card{background:rgba(10,16,26,.9);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:18px}.bs-card h3,.bs-card h4{margin-top:0}.bs-card p{line-height:1.55}.bs-meta{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#7dd3fc}.bs-chip{display:inline-block;padding:4px 8px;border-radius:999px;background:rgba(90,223,255,.12);color:#8fe8ff;font-size:12px;margin:2px}.bs-story{white-space:pre-wrap;line-height:1.7}.bs-warning{border-left:3px solid #f59e0b;padding-left:12px}.bs-merch{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.bs-merch-art{aspect-ratio:16/10;border-radius:14px;background:radial-gradient(circle at 50% 35%,rgba(90,223,255,.22),rgba(4,9,17,.96) 58%);display:grid;place-items:center;font-weight:800;letter-spacing:.12em;color:#dff8ff;border:1px dashed rgba(90,223,255,.35);text-align:center;padding:18px}.bs-status{display:flex;gap:10px;align-items:center}.bs-dot{width:9px;height:9px;border-radius:50%;background:#f59e0b}.bs-dot.ok{background:#22c55e}@media(max-width:800px){#blackstar .bs-hero{grid-template-columns:1fr}}
  `; document.head.appendChild(s);
}

async function loadBible(){
  const r=await fetch('./episodes/blackstar-s01e01/show-bible.json',{cache:'no-store'});
  if(!r.ok) throw new Error('Could not load BLACKSTAR show bible.');
  return r.json();
}

function characterCard(c){return `<article class="bs-card"><div class="bs-meta">${esc(c.role)}</div><h3>${esc(c.name)}</h3><p><strong>Public face:</strong> ${esc(c.public_face)}</p><p><strong>Backstory:</strong> ${esc(c.backstory)}</p><p><strong>Secret:</strong> ${esc(c.secret)}</p><p><strong>Season arc:</strong> ${esc(c.season_arc)}</p><p><strong>Visual signature:</strong> ${esc(c.visual_signature)}</p><div>${(c.merch_motifs||[]).map(x=>`<span class="bs-chip">${esc(x)}</span>`).join('')}</div></article>`}
function episodeCard(e){return `<article class="bs-card"><div class="bs-meta">Episode ${e.number}</div><h3>${esc(e.title)}</h3><p>${esc(e.purpose)}</p></article>`}
function merchCard(p){return `<article class="bs-card"><div class="bs-merch-art">${esc(p.name)}<br><small>${esc(p.sku)}</small></div><h3>${esc(p.name)}</h3><p>${esc(p.art)}</p><p class="muted small">Placement: ${esc(p.placement)}</p><button class="ghost compact" data-bs-merch="${esc(p.sku)}">Prepare product</button></article>`}

function render(root,b){
  root.innerHTML=`
    <section class="bs-hero"><div><div class="eyebrow">ORIGINAL SERIES COMMAND</div><h2 class="bs-title">${esc(b.show.title)}</h2><p style="font-size:20px">${esc(b.show.tagline)}</p><p class="muted">${esc(b.show.premise)}</p><div>${b.show.themes.map(x=>`<span class="bs-chip">${esc(x)}</span>`).join('')}</div></div><div class="bs-card"><div class="bs-meta">Identity</div><h3>BLACKSTAR team mark</h3><p>${esc(b.show.team_mark)}</p><p>${esc(b.show.logo_rule)}</p><p class="muted small">${esc(b.show.visual_identity)}</p></div></section>
    <div class="bs-tabs">${['overview','script','characters','lore','production','audio','merch'].map((x,i)=>`<button class="bs-subtab ${i?'':'active'}" data-bs-tab="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div>
    <section class="bs-panel active" data-bs-panel="overview"><div class="bs-grid"><article class="bs-card"><div class="bs-meta">Season One</div><h3>Complete season arc</h3><p>${esc(b.season_one.arc)}</p></article><article class="bs-card"><div class="bs-meta">Episode One</div><h3>${esc(b.episode_one.title)}</h3><p>${esc(b.episode_one.full_story)}</p></article></div><h3>Season map</h3><div class="bs-grid">${b.season_one.episodes.map(episodeCard).join('')}</div></section>
    <section class="bs-panel" data-bs-panel="script"><article class="bs-card"><div class="bs-meta">Story treatment</div><h3>S1E1 — ${esc(b.episode_one.title)}</h3><p class="bs-story">${esc(b.episode_one.full_story)}</p><p class="bs-warning"><strong>Violence rule:</strong> ${esc(b.episode_one.death_and_danger_rule)}</p><a class="ghost compact" href="./episodes/blackstar-s01e01/episode.json" target="_blank" rel="noopener">Open 20-segment production script</a></article></section>
    <section class="bs-panel" data-bs-panel="characters"><div class="bs-grid">${b.characters.map(characterCard).join('')}</div></section>
    <section class="bs-panel" data-bs-panel="lore"><div class="bs-grid">${b.easter_eggs.map(e=>`<article class="bs-card"><div class="bs-meta">${esc(e.id)}</div><h3>Seed</h3><p>${esc(e.seed)}</p><h4>Payoff</h4><p>${esc(e.payoff)}</p></article>`).join('')}</div></section>
    <section class="bs-panel" data-bs-panel="production"><div class="bs-grid"><article class="bs-card"><div class="bs-meta">Animation direction</div><h3>Animation targets</h3>${b.episode_one.animation_targets.map(x=>`<p>• ${esc(x)}</p>`).join('')}</article><article class="bs-card"><div class="bs-meta">Shared render system</div><h3>Continuity locked across 20 workers</h3><p>Every BLACKSTAR renderer uses the same show bible, stable character IDs, common environment library, palette, camera language and story continuity contract. Background plates are generated once, hashed, then shared rather than regenerated independently.</p></article><article class="bs-card"><div class="bs-meta">Action language</div><h3>Explosions, danger and deaths</h3><p>${esc(b.episode_one.death_and_danger_rule)}</p><p>Explosions should combine flash, debris, pressure-wave motion, environmental reaction, layered low-frequency sound and aftermath damage. Deaths should change later character behavior and story decisions.</p></article></div></section>
    <section class="bs-panel" data-bs-panel="audio"><div class="bs-grid"><article class="bs-card"><div class="bs-meta">Original score</div><h3>Soundtrack language</h3><p>${esc(b.episode_one.soundtrack)}</p></article><article class="bs-card"><div class="bs-meta">Sound design</div><h3>SFX palette</h3><p>${esc(b.episode_one.sfx)}</p></article></div></section>
    <section class="bs-panel" data-bs-panel="merch"><div class="bs-card"><div class="section-head"><div><div class="bs-meta">Store connection</div><h3>BLACKSTAR merchandise</h3></div><div class="bs-status"><span class="bs-dot"></span><span>${esc(b.merch.store_connection.status)}</span></div></div><p>${esc(b.merch.store_connection.note)}</p><p class="muted small">Canon rule: merch art must use approved BLACKSTAR character IDs, team/logo rules and artwork revisioning. Product preparation does not publish to an external store until that store is connected.</p></div><div class="bs-merch" style="margin-top:16px">${b.merch.products.map(merchCard).join('')}</div></section>`;
  root.addEventListener('click',e=>{const t=e.target.closest('[data-bs-tab]');if(t){root.querySelectorAll('.bs-subtab').forEach(x=>x.classList.toggle('active',x===t));root.querySelectorAll('.bs-panel').forEach(x=>x.classList.toggle('active',x.dataset.bsPanel===t.dataset.bsTab));}const m=e.target.closest('[data-bs-merch]');if(m){alert(`BLACKSTAR ${m.dataset.bsMerch} is canon-approved and ready for artwork/store mapping. External publishing is disabled until the exact merch provider is connected.`);}});
}

async function init(){style();const root=document.getElementById('blackstarRoot');if(!root)return;root.innerHTML='<div class="panel">Loading BLACKSTAR canon…</div>';try{render(root,await loadBible())}catch(e){root.innerHTML=`<div class="panel"><strong>BLACKSTAR UI error</strong><p>${esc(e.message)}</p></div>`}}
init();
