// Rolixa public YouTube publishing. Finished QC-cleared videos publish directly as Public.
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=createClient('https://uqmnpeovwfzizajheuig.supabase.co','sb_publishable_W6N3YZeKf9iMSpQMt4Oukw_rmLfRTap');
const workspace=document.getElementById('projectWorkspace');let timer=null,rendering=false,publishingAll=false;
function selectedProjectId(){return document.querySelector('.project-button.selected')?.dataset.openProject||null;}
function statusLine(text){const p=document.createElement('p');p.className='status-line';p.textContent=text;return p;}
async function publish(projectId){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Your Rolixa session expired. Sign in again.');const response=await fetch('/api/youtube-publish',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({projectId,privacyStatus:'public',description:'Original video created and produced with Rolixa.'})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`YouTube upload failed (${response.status}).`);return body;}
async function publishAll(status,button){if(publishingAll)return;publishingAll=true;button.disabled=true;try{const {data:projects,error}=await supabase.from('video_projects').select('id,title,status,output_url').in('status',['ready','quality_check']).not('output_url','is',null).order('created_at',{ascending:true});if(error)throw error;if(!projects?.length){status.textContent='No finished videos are waiting to publish.';return;}let ok=0,failed=0;for(const p of projects){status.textContent=`Publishing ${ok+failed+1} of ${projects.length}: ${p.title}…`;try{await publish(p.id);ok++;}catch(e){failed++;console.error('Publish All',p.id,e);}}status.textContent=`Publish All finished: ${ok} public, ${failed} failed.`;setTimeout(()=>location.reload(),1800);}catch(e){status.textContent=e?.message||'Publish All failed.';}finally{publishingAll=false;button.disabled=false;}}
function installPublishAll(){const videos=document.getElementById('videos');const head=videos?.querySelector('.page-head');if(!head||document.getElementById('publishAllBtn'))return;const wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:10px;align-items:center;flex-wrap:wrap';const btn=document.createElement('button');btn.id='publishAllBtn';btn.className='primary compact';btn.type='button';btn.textContent='Publish All Public';const st=document.createElement('span');st.id='publishAllStatus';st.className='status-line';wrap.append(btn,st);const refresh=document.getElementById('refreshBtn');refresh?.parentElement?.appendChild(wrap);btn.onclick=()=>publishAll(st,btn);}
async function refreshPanel(){installPublishAll();if(!workspace||rendering)return;const projectId=selectedProjectId();if(!projectId)return;rendering=true;try{const {data:p}=await supabase.from('video_projects').select('id,title,status,output_url,published_at').eq('id',projectId).maybeSingle();if(!p)return;document.getElementById('youtubePublishPanel')?.remove();const panel=document.createElement('section');panel.id='youtubePublishPanel';panel.className='work-card wide-card';panel.innerHTML='<div class="eyebrow">YOUTUBE PUBLISH</div><h3>Public publishing</h3>';if(p.status==='posted')panel.appendChild(statusLine('Published publicly on YouTube.'));else if(['ready','quality_check'].includes(p.status)&&p.output_url){const copy=document.createElement('p');copy.className='muted small';copy.textContent='Finished videos publish directly to Public. No publishing checklist or private staging.';panel.appendChild(copy);const btn=document.createElement('button');btn.type='button';btn.className='primary compact';btn.textContent='Publish Public Now';const st=statusLine('Ready for public upload.');panel.append(btn,st);btn.onclick=async()=>{btn.disabled=true;st.textContent='Uploading publicly to YouTube…';try{await publish(projectId);st.textContent='Published publicly.';setTimeout(()=>location.reload(),1200);}catch(e){st.textContent=e?.message||'Publish failed.';btn.disabled=false;}};}else panel.appendChild(statusLine(`Project is ${p.status}. Public upload starts when a finished QC-cleared MP4 exists.`));(workspace.querySelector('.work-grid')||workspace).appendChild(panel);}finally{rendering=false;}}
function refreshSoon(){clearTimeout(timer);timer=setTimeout(refreshPanel,100);}installPublishAll();if(workspace){new MutationObserver(refreshSoon).observe(workspace,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('[data-open-project],[data-view="videos"]'))refreshSoon();});refreshSoon();}