import hashlib, json, os, random, urllib.parse, urllib.request
from datetime import datetime, timezone, timedelta
SUPABASE_URL=os.environ.get('SUPABASE_URL','').rstrip('/');SERVICE_KEY=os.environ.get('SUPABASE_SERVICE_ROLE_KEY','')
if not SUPABASE_URL or not SERVICE_KEY:raise SystemExit('Supabase secrets required.')
HEADERS={'apikey':SERVICE_KEY,'Authorization':f'Bearer {SERVICE_KEY}','Content-Type':'application/json'}
def req(method,path,data=None,prefer=None):
 body=None if data is None else json.dumps(data).encode();h=dict(HEADERS)
 if prefer:h['Prefer']=prefer
 r=urllib.request.Request(SUPABASE_URL+path,data=body,headers=h,method=method)
 with urllib.request.urlopen(r,timeout=60) as res:raw=res.read();return json.loads(raw.decode()) if raw else None
def seed_for(series_id,episode_number):return int(hashlib.sha256(f'{series_id}:{episode_number}'.encode()).hexdigest()[:16],16)
def choose(rng,items):return items[rng.randrange(len(items))]
def prior_episode(series_id):
 rows=req('GET',f"/rest/v1/series_episodes?series_id=eq.{series_id}&select=episode_number,chapter_title,synopsis,continuity&order=episode_number.desc&limit=1") or [];return rows[0] if rows else None
def ensure_master(series):
 bible=series.get('story_bible') or {};master=bible.get('master_story') or {}
 if not master:
  chars=bible.get('characters') or ['Mara','Jax','Niko','Vale'];master={'logline':f"{series['premise']} One continuous escalating story follows {', '.join(chars[:5])} as every discovery changes the next choice.",'central_question':'What is really happening, who can be trusted, and what will the characters sacrifice to reach the truth?','acts':[{'name':'Act I — Discovery','range':[1,20]},{'name':'Act II — Escalation','range':[21,45]},{'name':'Act III — Fracture','range':[46,70]},{'name':'Act IV — Reckoning','range':[71,90]},{'name':'Act V — Resolution','range':[91,100]}],'open_threads':['the central mystery','the cost of the first discovery','a trust fracture inside the group'],'resolved_threads':[],'ending':'Resolve the central mystery and major character promises after the final act.'};bible['master_story']=master
 return bible,master
def act_for(master,n):
 for a in master.get('acts',[]):
  lo,hi=a.get('range',[1,100])
  if lo<=n<=hi:return a.get('name','Continuing arc')
 return 'Continuing arc'
def animated_story(series,episode_number):
 rng=random.Random(seed_for(series['id'],episode_number));bible,master=ensure_master(series);chars=bible.get('characters') or ['Mara','Jax','Niko','Vale'];lead=chars[(episode_number-1)%len(chars)];ally=chars[episode_number%len(chars)];previous=prior_episode(series['id']);carry=(previous or {}).get('continuity') or bible.get('last_continuity') or {};prior=carry.get('cliffhanger') or carry.get('open_loop') or 'the discovery they barely escaped with';act=act_for(master,episode_number)
 places=['the flooded observation dome','the bioluminescent market','the old tide-control tunnels','the abandoned research pier','the deep-water transit lock','the storm-lit harbor wall','the sealed archive below the marina','the reef beyond the warning buoys'];place=choose(rng,places);thread=choose(rng,master.get('open_threads') or ['the central mystery']);turn=choose(rng,['evidence that contradicts the safest explanation','a clue tied to something everyone dismissed earlier','proof that a trusted story cannot be true','a warning that is actually a map','a hidden record that changes who can be trusted','a device reacting to a name no one expected']);chapter_name=choose(rng,['The Signal Below','A Door That Should Not Open','The Missing Current','What the Lights Remember','The Name in the Archive','Pressure Line','The False Safe Harbor','The Last Quiet Warning']);title=f'Chapter {episode_number}: {chapter_name}';cliff=f'A final detail links {thread} to {ally}, forcing {lead} into a dangerous choice in Chapter {episode_number+1}.'
 hook=f'{lead} thought the last discovery was the dangerous part, but the consequence waiting at {place} is worse.'
 lines=[hook,f'They arrive carrying one problem they cannot leave behind: {prior}.',f'{ally} wants to slow down, but {lead} notices {turn}, and suddenly the same mystery they have been chasing points in a different direction.',f'The clue connects directly to {thread}, so walking away would mean ignoring something the group already paid a price to learn.',f'They test the idea instead of guessing, and the result changes the situation permanently: a route closes, a secret is exposed, and one safe option disappears.',f'{ally} argues for the explanation that keeps everyone together, while {lead} realizes the evidence makes that comfort impossible.',f'An overlooked detail from the previous chapter finally makes sense, proving the story has been moving toward this moment rather than starting over.',f'Inside {act}, the stakes rise because the next choice can no longer protect both the mission and the people involved.',f'Just when they think they understand what the clue means, {cliff}'];script=' '.join(lines)
 continuity={'chapter':episode_number,'act':act,'lead':lead,'ally':ally,'location':place,'advanced_thread':thread,'previous_cliffhanger':prior,'cliffhanger':cliff,'open_loop':cliff,'master_logline':master.get('logline'),'shot_plan':{'location':place,'required_character_consistency':[lead,ally],'payoff_previous':True,'ending_handoff':True}};synopsis=f'{lead} follows the previous consequence into {place}, where new evidence advances {thread}, changes the group’s understanding of the master mystery, and creates the decision that drives the next chapter.';return title,synopsis,hook,script,continuity,bible
def documentary_story(series,episode_number):
 bible,master=ensure_master(series);facts=bible.get('verified_facts') or []
 if not facts:raise RuntimeError('Documentary series needs story_bible.verified_facts before automatic factual episode generation.')
 rng=random.Random(seed_for(series['id'],episode_number));fact=facts[(episode_number-1)%len(facts)];fact_text=str((fact.get('fact') or fact.get('claim')) if isinstance(fact,dict) else fact).strip();source=str(fact.get('source') or '') if isinstance(fact,dict) else '';previous=prior_episode(series['id']);prior=((previous or {}).get('continuity') or {}).get('open_loop') or 'the consequence established in the previous chapter';act=act_for(master,episode_number);title=f'Chapter {episode_number}: {choose(rng,["The Detail That Changes Everything","The Hidden Turning Point","The Consequence","What Happened Next"])}';hook=f'The important part of this story is not just what happened, but what that verified detail forced to happen next.';script=' '.join([hook,f'The previous chapter left us with {prior}.',f'The verified record now gives us the next solid piece: {fact_text}.',f'On its own that fact can sound isolated, but inside the same timeline it changes how we understand the central question: {master.get("central_question")}',f'The useful step is to follow cause and consequence rather than stack unrelated trivia.',f'This evidence narrows the possibilities, rules out at least one easy explanation, and shows why the next decision or event matters.',f'What came before now has a measurable consequence, which is why this chapter belongs to the same story instead of becoming a separate fact list.',f'Inside {act}, the evidence moves the narrative forward while the source remains traceable and the uncertain parts stay uncertain.',f'The next chapter follows the direct verified consequence of this event, not a new subject.']);continuity={'fact':fact_text,'source':source,'act':act,'open_loop':'Follow the direct verified consequence in the next chapter.','master_logline':master.get('logline'),'shot_plan':{'evidence_led':True,'source':source,'timeline_continuity':True}};return title,'A connected evidence-led chapter in the same long-form documentary narrative.',hook,script,continuity,bible
def generate_one(series):
 ep=int(series['next_episode_number']);prior=prior_episode(series['id'])
 if prior and int(prior['episode_number'])>=ep:raise RuntimeError('Duplicate episode blocked.')
 if series['series_type']=='documentary':chapter,synopsis,hook,script,continuity,bible=documentary_story(series,ep)
 else:chapter,synopsis,hook,script,continuity,bible=animated_story(series,ep)
 project=(req('POST','/rest/v1/video_projects',{'user_id':series['user_id'],'title':f"{series['title']} — {chapter}",'topic':synopsis,'format':'Story','style':'Documentary' if series['series_type']=='documentary' else 'Storytime','target_duration_seconds':series['episode_length_seconds'],'status':'generating','hook':hook,'script':script},'return=representation') or [None])[0]
 if not project:raise RuntimeError('Could not create episode video project.')
 req('POST','/rest/v1/series_episodes',{'user_id':series['user_id'],'series_id':series['id'],'episode_number':ep,'chapter_title':chapter,'synopsis':synopsis,'script':script,'continuity':continuity,'video_project_id':project['id'],'status':'generating'},'return=minimal')
 steps=[]
 for step,status,detail in [('research','running' if series['series_type']=='documentary' else 'passed','Master story and continuity loaded.'),('script','passed','Finished spoken narration advances the master story; production directions remain in continuity metadata.'),('creative_preflight','pending','Waiting for automatic creative director score.'),('voice','running','Queued for expressive narration.'),('visuals','running','Queued for motion-first scene planning.'),('edit','running','Queued for retention-focused edit.'),('sound_design','pending','Sound design runs after picture lock.'),('final_video_qc','pending','Finished MP4 must pass before publishing.'),('quality_check','pending',None),('ready','pending',None)]:steps.append({'user_id':series['user_id'],'project_id':project['id'],'step':step,'status':status,'detail':detail})
 req('POST','/rest/v1/project_pipeline_steps',steps,'resolution=merge-duplicates,return=minimal');req('POST','/rest/v1/hook_variants',{'user_id':series['user_id'],'project_id':project['id'],'hook':hook,'selected':True},'return=minimal');req('POST','/rest/v1/render_jobs',{'user_id':series['user_id'],'project_id':project['id'],'status':'queued'},'return=minimal');now=datetime.now(timezone.utc);bible['last_continuity']=continuity;req('PATCH',f"/rest/v1/series_projects?id=eq.{series['id']}",{'next_episode_number':ep+1,'last_generated_at':now.isoformat(),'next_run_at':(now+timedelta(days=1)).isoformat(),'story_bible':bible,'updated_at':now.isoformat()},'return=minimal');print(f"Queued connected {series['title']} chapter {ep}: {chapter}")
now=urllib.parse.quote(datetime.now(timezone.utc).isoformat(),safe='');series=req('GET',f'/rest/v1/series_projects?status=eq.active&cadence=eq.daily&or=(next_run_at.is.null,next_run_at.lte.{now})&select=*&order=created_at.asc') or []
if not series:print('No due series episodes.')
else:
 for item in series:
  try:generate_one(item)
  except Exception as exc:print(f"Series {item.get('id')} skipped: {exc}")
